// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/proto/monitoring.proto

package monitoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRequest) Reset() {
	*x = DeviceRequest{}
	mi := &file_internal_proto_monitoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRequest) ProtoMessage() {}

func (x *DeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_monitoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRequest.ProtoReflect.Descriptor instead.
func (*DeviceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_monitoring_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_internal_proto_monitoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_monitoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_internal_proto_monitoring_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Device) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	HwVersion     string                 `protobuf:"bytes,4,opt,name=hw_version,json=hwVersion,proto3" json:"hw_version,omitempty"`
	SwVersion     string                 `protobuf:"bytes,5,opt,name=sw_version,json=swVersion,proto3" json:"sw_version,omitempty"`
	FwVersion     string                 `protobuf:"bytes,6,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	Checksum      string                 `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_internal_proto_monitoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_monitoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_internal_proto_monitoring_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceStatus) GetHwVersion() string {
	if x != nil {
		return x.HwVersion
	}
	return ""
}

func (x *DeviceStatus) GetSwVersion() string {
	if x != nil {
		return x.SwVersion
	}
	return ""
}

func (x *DeviceStatus) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *DeviceStatus) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type DeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	HwVersion     string                 `protobuf:"bytes,2,opt,name=hw_version,json=hwVersion,proto3" json:"hw_version,omitempty"`
	SwVersion     string                 `protobuf:"bytes,3,opt,name=sw_version,json=swVersion,proto3" json:"sw_version,omitempty"`
	FwVersion     string                 `protobuf:"bytes,4,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusResponse) Reset() {
	*x = DeviceStatusResponse{}
	mi := &file_internal_proto_monitoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusResponse) ProtoMessage() {}

func (x *DeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_monitoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_monitoring_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceStatusResponse) GetHwVersion() string {
	if x != nil {
		return x.HwVersion
	}
	return ""
}

func (x *DeviceStatusResponse) GetSwVersion() string {
	if x != nil {
		return x.SwVersion
	}
	return ""
}

func (x *DeviceStatusResponse) GetFwVersion() string {
	if x != nil {
		return x.FwVersion
	}
	return ""
}

func (x *DeviceStatusResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_internal_proto_monitoring_proto protoreflect.FileDescriptor

const file_internal_proto_monitoring_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/monitoring.proto\x12\n" +
	"monitoring\"\x1f\n" +
	"\rDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"\xcc\x01\n" +
	"\fDeviceStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"hw_version\x18\x04 \x01(\tR\thwVersion\x12\x1d\n" +
	"\n" +
	"sw_version\x18\x05 \x01(\tR\tswVersion\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x06 \x01(\tR\tfwVersion\x12\x1a\n" +
	"\bchecksum\x18\a \x01(\tR\bchecksum\"\xa7\x01\n" +
	"\x14DeviceStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"hw_version\x18\x02 \x01(\tR\thwVersion\x12\x1d\n" +
	"\n" +
	"sw_version\x18\x03 \x01(\tR\tswVersion\x12\x1d\n" +
	"\n" +
	"fw_version\x18\x04 \x01(\tR\tfwVersion\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum2\xe2\x01\n" +
	"\n" +
	"Monitoring\x12:\n" +
	"\tGetDevice\x12\x19.monitoring.DeviceRequest\x1a\x12.monitoring.Device\x12F\n" +
	"\x0fGetDeviceStatus\x12\x19.monitoring.DeviceRequest\x1a\x18.monitoring.DeviceStatus\x12P\n" +
	"\x11CheckDeviceStatus\x12\x19.monitoring.DeviceRequest\x1a .monitoring.DeviceStatusResponseB-Z+device-monitoring/internal/proto;monitoringb\x06proto3"

var (
	file_internal_proto_monitoring_proto_rawDescOnce sync.Once
	file_internal_proto_monitoring_proto_rawDescData []byte
)

func file_internal_proto_monitoring_proto_rawDescGZIP() []byte {
	file_internal_proto_monitoring_proto_rawDescOnce.Do(func() {
		file_internal_proto_monitoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_monitoring_proto_rawDesc), len(file_internal_proto_monitoring_proto_rawDesc)))
	})
	return file_internal_proto_monitoring_proto_rawDescData
}

var file_internal_proto_monitoring_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_monitoring_proto_goTypes = []any{
	(*DeviceRequest)(nil),        // 0: monitoring.DeviceRequest
	(*Device)(nil),               // 1: monitoring.Device
	(*DeviceStatus)(nil),         // 2: monitoring.DeviceStatus
	(*DeviceStatusResponse)(nil), // 3: monitoring.DeviceStatusResponse
}
var file_internal_proto_monitoring_proto_depIdxs = []int32{
	0, // 0: monitoring.Monitoring.GetDevice:input_type -> monitoring.DeviceRequest
	0, // 1: monitoring.Monitoring.GetDeviceStatus:input_type -> monitoring.DeviceRequest
	0, // 2: monitoring.Monitoring.CheckDeviceStatus:input_type -> monitoring.DeviceRequest
	1, // 3: monitoring.Monitoring.GetDevice:output_type -> monitoring.Device
	2, // 4: monitoring.Monitoring.GetDeviceStatus:output_type -> monitoring.DeviceStatus
	3, // 5: monitoring.Monitoring.CheckDeviceStatus:output_type -> monitoring.DeviceStatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_monitoring_proto_init() }
func file_internal_proto_monitoring_proto_init() {
	if File_internal_proto_monitoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_monitoring_proto_rawDesc), len(file_internal_proto_monitoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_monitoring_proto_goTypes,
		DependencyIndexes: file_internal_proto_monitoring_proto_depIdxs,
		MessageInfos:      file_internal_proto_monitoring_proto_msgTypes,
	}.Build()
	File_internal_proto_monitoring_proto = out.File
	file_internal_proto_monitoring_proto_goTypes = nil
	file_internal_proto_monitoring_proto_depIdxs = nil
}
