
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=monitor
    networks:
      monitor-network:
        ipv4_address: 172.30.0.3

#  checksum-service:
#    build:
#      context: .
#      dockerfile: ./cmd/checksum-generator/Dockerfile
#    container_name: checksum-generator
#    entrypoint: ["checksum-bin", "--input=example"]
#    networks:
#      monitor-network:

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitor
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      monitor-network:
        ipv4_address: 172.30.0.2

volumes:
  pgdata:

networks:
  monitor-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
