// Code generated by protoc-gen-go. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

type DeviceRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

type Device struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress string `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Protocol  string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

type DeviceStatus struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId  string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status    string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	HwVersion string `protobuf:"bytes,4,opt,name=hw_version,json=hwVersion,proto3" json:"hw_version,omitempty"`
	SwVersion string `protobuf:"bytes,5,opt,name=sw_version,json=swVersion,proto3" json:"sw_version,omitempty"`
	FwVersion string `protobuf:"bytes,6,opt,name=fw_version,json=fwVersion,proto3" json:"fw_version,omitempty"`
	Checksum  string `protobuf:"bytes,7,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

// DeviceMonitoringClient defines the client API.
type DeviceMonitoringClient interface {
	GetDevice(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*Device, error)
	GetDeviceStatus(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceStatus, error)
}

type deviceMonitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceMonitoringClient(cc grpc.ClientConnInterface) DeviceMonitoringClient {
	return &deviceMonitoringClient{cc}
}

func (c *deviceMonitoringClient) GetDevice(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*Device, error) {
	// stub
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}

func (c *deviceMonitoringClient) GetDeviceStatus(ctx context.Context, in *DeviceRequest, opts ...grpc.CallOption) (*DeviceStatus, error) {
	// stub
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceStatus not implemented")
}
